-- Comprehensive Chemotherapy Regimen Components View
-- Generated from RADIANT Unified Chemotherapy Index
-- Total components: 75
-- Source: /Users/resnick/Downloads/RADIANT_Portal/RADIANT_PCA/unified_chemo_index/regimen_components.csv

CREATE OR REPLACE VIEW fhir_prd_db.v_chemotherapy_regimen_components AS
SELECT regimen_id, order_index, component_drug_id, component_name_original, component_role
FROM (
  VALUES
    ('regimen:pcv', 1, 'rx:8702.0', 'procarbazine', 'core'),
    ('regimen:pcv', 2, 'rx:6466.0', 'lomustine', 'core'),
    ('regimen:pcv', 3, 'rx:11202.0', 'vincristine', 'core'),
    ('regimen:abvd', 1, 'rx:3639.0', 'doxorubicin', 'core'),
    ('regimen:abvd', 2, NULL, 'bleomycin', 'core'),
    ('regimen:abvd', 3, 'rx:11198.0', 'vinblastine', 'core'),
    ('regimen:abvd', 4, 'rx:3098.0', 'dacarbazine', 'core'),
    ('regimen:chop', 1, 'rx:3002.0', 'cyclophosphamide', 'core'),
    ('regimen:chop', 2, 'rx:3639.0', 'doxorubicin', 'core'),
    ('regimen:chop', 3, 'rx:11202.0', 'vincristine', 'core'),
    ('regimen:chop', 4, 'rx:8640.0', 'prednisone', 'core'),
    ('regimen:rchop', 1, 'rx:121191.0', 'rituximab', 'core'),
    ('regimen:rchop', 2, 'rx:3002.0', 'cyclophosphamide', 'core'),
    ('regimen:rchop', 3, 'rx:3639.0', 'doxorubicin', 'core'),
    ('regimen:rchop', 4, 'rx:11202.0', 'vincristine', 'core'),
    ('regimen:rchop', 5, 'rx:8640.0', 'prednisone', 'core'),
    ('regimen:bep', 1, NULL, 'bleomycin', 'core'),
    ('regimen:bep', 2, 'rx:4179.0', 'etoposide', 'core'),
    ('regimen:bep', 3, 'rx:2555.0', 'cisplatin', 'core'),
    ('regimen:folfirinox', 1, NULL, 'leucovorin', 'core'),
    ('regimen:folfirinox', 2, 'rx:4492.0', 'fluorouracil', 'core'),
    ('regimen:folfirinox', 3, 'rx:51499.0', 'irinotecan', 'core'),
    ('regimen:folfirinox', 4, 'rx:32592.0', 'oxaliplatin', 'core'),
    ('regimen:folfox', 1, NULL, 'leucovorin', 'core'),
    ('regimen:folfox', 2, 'rx:4492.0', 'fluorouracil', 'core'),
    ('regimen:folfox', 3, 'rx:32592.0', 'oxaliplatin', 'core'),
    ('regimen:folfiri', 1, NULL, 'leucovorin', 'core'),
    ('regimen:folfiri', 2, 'rx:4492.0', 'fluorouracil', 'core'),
    ('regimen:folfiri', 3, 'rx:51499.0', 'irinotecan', 'core'),
    ('regimen:capox', 1, 'rx:194000.0', 'capecitabine', 'core'),
    ('regimen:capox', 2, 'rx:32592.0', 'oxaliplatin', 'core'),
    ('regimen:ac', 1, 'rx:3639.0', 'doxorubicin', 'core'),
    ('regimen:ac', 2, 'rx:3002.0', 'cyclophosphamide', 'core'),
    ('regimen:tchp', 1, 'rx:72962.0', 'docetaxel', 'core'),
    ('regimen:tchp', 2, 'rx:40048.0', 'carboplatin', 'core'),
    ('regimen:tchp', 3, 'rx:224905.0', 'trastuzumab', 'core'),
    ('regimen:tchp', 4, 'rx:1298944.0', 'pertuzumab', 'core'),
    ('regimen:tip', 1, 'rx:56946.0', 'paclitaxel', 'core'),
    ('regimen:tip', 2, 'rx:5657.0', 'ifosfamide', 'core'),
    ('regimen:tip', 3, 'rx:2555.0', 'cisplatin', 'core'),
    ('regimen:ice', 1, 'rx:5657.0', 'ifosfamide', 'core'),
    ('regimen:ice', 2, 'rx:40048.0', 'carboplatin', 'core'),
    ('regimen:ice', 3, 'rx:4179.0', 'etoposide', 'core'),
    ('regimen:dhap', 1, 'rx:3264.0', 'dexamethasone', 'core'),
    ('regimen:dhap', 2, 'rx:3041.0', 'cytarabine', 'core'),
    ('regimen:dhap', 3, 'rx:2555.0', 'cisplatin', 'core'),
    ('regimen:epochr', 1, 'rx:4179.0', 'etoposide', 'core'),
    ('regimen:epochr', 2, 'rx:8640.0', 'prednisone', 'core'),
    ('regimen:epochr', 3, 'rx:11202.0', 'vincristine', 'core'),
    ('regimen:epochr', 4, 'rx:3002.0', 'cyclophosphamide', 'core'),
    ('regimen:epochr', 5, 'rx:3639.0', 'doxorubicin', 'core'),
    ('regimen:epochr', 6, 'rx:121191.0', 'rituximab', 'core'),
    ('regimen:hypercvad', 1, 'rx:3002.0', 'cyclophosphamide', 'core'),
    ('regimen:hypercvad', 2, 'rx:11202.0', 'vincristine', 'core'),
    ('regimen:hypercvad', 3, 'rx:3639.0', 'doxorubicin', 'core'),
    ('regimen:hypercvad', 4, 'rx:3264.0', 'dexamethasone', 'core'),
    ('regimen:hypercvad', 5, 'rx:6851.0', 'methotrexate', 'core'),
    ('regimen:hypercvad', 6, 'rx:3041.0', 'cytarabine', 'core'),
    ('regimen:flagida', 1, 'rx:24698.0', 'fludarabine', 'core'),
    ('regimen:flagida', 2, 'rx:3041.0', 'cytarabine', 'core'),
    ('regimen:flagida', 3, 'rx:68442.0', 'filgrastim', 'core'),
    ('regimen:flagida', 4, 'rx:5650.0', 'idarubicin', 'core'),
    ('regimen:atraato', 1, NULL, 'tretinoin', 'core'),
    ('regimen:atraato', 2, 'rx:18330.0', 'arsenic trioxide', 'core'),
    ('regimen:tc', 1, 'rx:72962.0', 'docetaxel', 'core'),
    ('regimen:tc', 2, 'rx:3002.0', 'cyclophosphamide', 'core'),
    ('regimen:cmf', 1, 'rx:3002.0', 'cyclophosphamide', 'core'),
    ('regimen:cmf', 2, 'rx:6851.0', 'methotrexate', 'core'),
    ('regimen:cmf', 3, 'rx:4492.0', 'fluorouracil', 'core'),
    ('regimen:captem', 1, 'rx:194000.0', 'capecitabine', 'core'),
    ('regimen:captem', 2, 'rx:37776.0', 'temozolomide', 'core'),
    ('regimen:rice', 1, 'rx:121191.0', 'rituximab', 'core'),
    ('regimen:rice', 2, 'rx:5657.0', 'ifosfamide', 'core'),
    ('regimen:rice', 3, 'rx:40048.0', 'carboplatin', 'core'),
    ('regimen:rice', 4, 'rx:4179.0', 'etoposide', 'core')
) AS regimen_components(regimen_id, order_index, component_drug_id, component_name_original, component_role);
